### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by huizi666** [geekplux/AR-AI-VIS-demo#1]
我下载了您的demo，能够跑起来了，我已经能够看到人脸识别，但是我不明确的是怎么去使用demo中ＡＲ、ＶＲ的一面，可能是我没有了解过这当面的知识，您是否能告诉我怎么体验demo？如果有困扰，万分抱歉

**Comment by geekplux** [comment]
其实这就已经是 AR 了啊，那个显示的框框你可以换成其他东西，人脸你也可以换成其他想识别的
